services:
  app-test:
    # เปลี่ยนจาก app เป็น app-test
    build: .
    ports:
      - '3011:3000'
    networks:
      - test-network # เปลี่ยนจาก app-network เป็น test-network

networks:
  test-network:
    # เปลี่ยนชื่อให้ตรงกัน
    driver: bridge
